const { Student, University, TimeTable, Organization } = require("../models");
const timeHelper = require("../helpers/timeHelper");
const { shouldCutMeal } = timeHelper;

// Các thời gian cố định cho bữa ăn
const MEAL_TIMES = {
  BREAKFAST: "06:00",
  LUNCH: "11:00",
  DINNER: "17:30",
};

// Tạo lịch cắt cơm tự động - DEPRECATED (chỉ dùng SQL)
const generateAutoCutRiceSchedule = async (studentId) => {
    "generateAutoCutRiceSchedule is deprecated, use generateCutRiceScheduleSQL instead"
  );
  return await generateCutRiceScheduleSQL(studentId);
};

// Cập nhật lịch cắt cơm tự động cho sinh viên - DEPRECATED (chỉ dùng SQL)
const updateAutoCutRice = async (studentId) => {
    "updateAutoCutRice is deprecated, use updateAutoCutRiceWithSchedule instead"
  );
  const cutRiceSchedule = await generateCutRiceScheduleSQL(studentId);
  return await updateAutoCutRiceWithSchedule(studentId, cutRiceSchedule);
};

// Cập nhật lịch cắt cơm với schedule có sẵn (tối ưu cho SQL)
const updateAutoCutRiceWithSchedule = async (studentId, cutRiceSchedule) => {
  try {
    const { CutRice } = require("../models");

    // Tìm lịch cắt cơm hiện có
    let existingCutRice = await CutRice.findOne({
      where: { studentId: studentId },
      order: [["createdAt", "DESC"]],
    });

    if (existingCutRice) {
      // Cập nhật lịch hiện có (sử dụng field weekly)
      await existingCutRice.update({
        weekly: cutRiceSchedule,
        isAutoGenerated: true, // Đánh dấu là tự động
        lastUpdated: new Date(),
        notes: "Tự động tạo dựa trên lịch học (SQL optimized)",
      });
    } else {
      // Tạo lịch mới (sử dụng field weekly)
      await CutRice.create({
        studentId: studentId,
        weekly: cutRiceSchedule,
        isAutoGenerated: true, // Đánh dấu là tự động
        lastUpdated: new Date(),
        notes: "Tự động tạo dựa trên lịch học (SQL optimized)",
      });
    }
    return cutRiceSchedule;
  } catch (error) {
    console.error("Error updating auto cut rice with schedule:", error);
    throw error;
  }
};

// Reset về lịch cắt cơm tự động - DEPRECATED (chỉ dùng SQL)
const resetToAutoCutRice = async (studentId) => {
    "resetToAutoCutRice is deprecated, use generateCutRiceScheduleSQL + updateAutoCutRiceWithSchedule instead"
  );
  const cutRiceSchedule = await generateCutRiceScheduleSQL(studentId);
  return await updateAutoCutRiceWithSchedule(studentId, cutRiceSchedule);
};

// Kiểm tra xem có cần cập nhật lịch cắt cơm không
const shouldUpdateCutRice = (lastUpdated) => {
  if (!lastUpdated) return true;

  const now = new Date();
  const diffInHours = (now - lastUpdated) / (1000 * 60 * 60);

  // Cập nhật nếu đã quá 24 giờ
  return diffInHours > 24;
};

// SQL function để tối ưu hóa việc tạo lịch cắt cơm
const generateCutRiceScheduleSQL = async (studentId) => {
  try {
    const { sequelize } = require("../services/sequelize");

    // Lấy thông tin organization để có travelTime
    const student = await Student.findByPk(studentId, {
      include: [Organization],
    });

    if (!student) {
      throw new Error("Không tìm thấy sinh viên");
    }

    const travelTime = student.organization?.travelTime || 45; // Mặc định 45 phút

    // SQL query tối ưu để tạo lịch cắt cơm dựa trên lịch học
    const query = `
      WITH meal_times AS (
        SELECT 'breakfast' as meal_type, '06:00'::time as meal_time
        UNION ALL
        SELECT 'lunch' as meal_type, '11:00'::time as meal_time  
        UNION ALL
        SELECT 'dinner' as meal_type, '17:30'::time as meal_time
      ),
      student_schedules AS (
        SELECT 
          tt."studentId" as student_id,
          jsonb_array_elements(tt.schedules) as schedule
        FROM time_tables tt
        WHERE tt."studentId" = $1
          AND tt.schedules IS NOT NULL
          AND jsonb_array_length(tt.schedules) > 0
      ),
      processed_schedules AS (
        SELECT 
          student_id,
          (schedule->>'day') as day,
          (schedule->>'startTime')::time as start_time,
          (schedule->>'endTime')::time as end_time,
          -- Tính thời gian đi (trừ travelTime phút)
          (schedule->>'startTime')::time - interval '${travelTime} minutes' as departure_time,
          -- Tính thời gian về (cộng travelTime phút)  
          (schedule->>'endTime')::time + interval '${travelTime} minutes' as return_time
        FROM student_schedules
        WHERE schedule->>'day' IS NOT NULL
          AND schedule->>'startTime' IS NOT NULL
          AND schedule->>'endTime' IS NOT NULL
          AND (schedule->>'startTime')::time IS NOT NULL
          AND (schedule->>'endTime')::time IS NOT NULL
      ),
      cut_rice_logic AS (
        SELECT 
          ps.student_id,
          ps.day,
          mt.meal_type,
          mt.meal_time,
          -- Logic cắt cơm đơn giản: Cắt cơm khi đi học ảnh hưởng đến giờ ăn
          CASE 
            -- Đi học qua giờ ăn (đi trước và về sau giờ ăn)
            WHEN ps.departure_time <= mt.meal_time AND ps.return_time >= mt.meal_time THEN true
            -- Đang học đúng vào giờ ăn
            WHEN ps.start_time <= mt.meal_time AND ps.end_time >= mt.meal_time THEN true
            -- Đi sớm hơn giờ ăn và về sau giờ ăn
            WHEN ps.departure_time < mt.meal_time AND ps.return_time > mt.meal_time THEN true
            ELSE false
          END as should_cut
        FROM processed_schedules ps
        CROSS JOIN meal_times mt
      )
      SELECT 
        student_id,
        day,
        jsonb_object_agg(meal_type, should_cut) as daily_schedule
      FROM cut_rice_logic
      WHERE should_cut = true
      GROUP BY student_id, day
    `;

    const results = await sequelize.query(query, {
      bind: [studentId],
      type: sequelize.QueryTypes.SELECT,
    });

    // Khởi tạo lịch cắt cơm mặc định
    const cutRiceSchedule = {
      monday: { breakfast: false, lunch: false, dinner: false },
      tuesday: { breakfast: false, lunch: false, dinner: false },
      wednesday: { breakfast: false, lunch: false, dinner: false },
      thursday: { breakfast: false, lunch: false, dinner: false },
      friday: { breakfast: false, lunch: false, dinner: false },
      saturday: { breakfast: false, lunch: false, dinner: false },
      sunday: { breakfast: false, lunch: false, dinner: false },
    };

    // Mapping ngày từ tiếng Việt sang tiếng Anh
    const dayMapping = {
      "Thứ 2": "monday",
      "Thứ 3": "tuesday",
      "Thứ 4": "wednesday",
      "Thứ 5": "thursday",
      "Thứ 6": "friday",
      "Thứ 7": "saturday",
      "Chủ nhật": "sunday",
    };

    // Cập nhật lịch cắt cơm từ kết quả SQL
    results.forEach((result) => {
      const englishDay = dayMapping[result.day];
      if (englishDay && result.daily_schedule) {
        cutRiceSchedule[englishDay] = {
          breakfast: result.daily_schedule.breakfast || false,
          lunch: result.daily_schedule.lunch || false,
          dinner: result.daily_schedule.dinner || false,
        };
      }
    });

    return cutRiceSchedule;
  } catch (error) {
    console.error("Error in generateCutRiceScheduleSQL:", error);
    throw error;
  }
};

module.exports = {
  generateAutoCutRiceSchedule,
  generateCutRiceScheduleSQL,
  updateAutoCutRice,
  updateAutoCutRiceWithSchedule,
  resetToAutoCutRice,
  shouldUpdateCutRice,
  MEAL_TIMES,
};
