-- CreateTable
CREATE TABLE "achievement_profiles" (
    "id" UUID NOT NULL,
    "studentId" UUID NOT NULL,
    "totalYears" INTEGER DEFAULT 0,
    "totalAdvancedSoldier" INTEGER DEFAULT 0,
    "totalCompetitiveSoldier" INTEGER DEFAULT 0,
    "totalScientificTopics" INTEGER DEFAULT 0,
    "totalScientificInitiatives" INTEGER DEFAULT 0,
    "eligibleForMinistryReward" BOOLEAN DEFAULT false,
    "eligibleForNationalReward" BOOLEAN DEFAULT false,
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "achievement_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "achievements" (
    "id" UUID NOT NULL,
    "studentId" UUID NOT NULL,
    "semester" VARCHAR(255),
    "schoolYear" VARCHAR(255),
    "content" TEXT,
    "year" INTEGER,
    "title" VARCHAR(255),
    "description" TEXT,
    "award" VARCHAR(255),
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "achievements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "classes" (
    "id" UUID NOT NULL,
    "className" VARCHAR(255) NOT NULL,
    "studentCount" INTEGER DEFAULT 0,
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),
    "educationLevelId" UUID,

    CONSTRAINT "classes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "commander_duty_schedules" (
    "id" SERIAL NOT NULL,
    "fullName" VARCHAR(255) NOT NULL,
    "rank" VARCHAR(255),
    "phoneNumber" VARCHAR(255),
    "position" VARCHAR(255),
    "workDay" TIMESTAMPTZ(6) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "commander_duty_schedules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "commanders" (
    "id" UUID NOT NULL,
    "commanderId" VARCHAR(255),
    "fullName" VARCHAR(255),
    "gender" VARCHAR(255),
    "birthday" TIMESTAMPTZ(6),
    "placeOfBirth" VARCHAR(255),
    "hometown" VARCHAR(255),
    "ethnicity" VARCHAR(255),
    "religion" VARCHAR(255),
    "currentAddress" VARCHAR(255),
    "email" VARCHAR(255),
    "phoneNumber" VARCHAR(255),
    "cccd" VARCHAR(255),
    "partyCardNumber" VARCHAR(255),
    "startWork" INTEGER,
    "organization" VARCHAR(255),
    "unit" VARCHAR(255),
    "rank" VARCHAR(255),
    "positionGovernment" VARCHAR(255),
    "positionParty" VARCHAR(255),
    "fullPartyMember" TIMESTAMPTZ(6),
    "probationaryPartyMember" TIMESTAMPTZ(6),
    "dateOfEnlistment" TIMESTAMPTZ(6),
    "avatar" VARCHAR(255) DEFAULT 'https://i.pinimg.com/736x/d4/a1/ff/d4a1ff9d0f243e50062e2b21f2f2496d.jpg',
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "commanders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "cut_rice" (
    "id" UUID NOT NULL,
    "studentId" UUID NOT NULL,
    "weekly" JSONB NOT NULL DEFAULT '{}',
    "isAutoGenerated" BOOLEAN DEFAULT true,
    "lastUpdated" TIMESTAMPTZ(6),
    "notes" VARCHAR(255),
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "cut_rice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "education_levels" (
    "id" UUID NOT NULL,
    "levelName" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),
    "organizationId" UUID,

    CONSTRAINT "education_levels_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" UUID NOT NULL,
    "studentId" UUID NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "content" TEXT,
    "isRead" BOOLEAN DEFAULT false,
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organizations" (
    "id" UUID NOT NULL,
    "organizationName" VARCHAR(255) NOT NULL,
    "travelTime" INTEGER NOT NULL DEFAULT 45,
    "totalStudents" INTEGER DEFAULT 0,
    "status" VARCHAR(255) DEFAULT 'active',
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),
    "universityId" UUID,

    CONSTRAINT "organizations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "scientific_initiatives" (
    "id" UUID NOT NULL,
    "yearlyAchievementId" UUID NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "year" INTEGER NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'pending',
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "scientific_initiatives_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "scientific_topics" (
    "id" UUID NOT NULL,
    "yearlyAchievementId" UUID NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "year" INTEGER NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'pending',
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "scientific_topics_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "semester_results" (
    "id" UUID NOT NULL,
    "studentId" UUID NOT NULL,
    "semester" VARCHAR(255) NOT NULL,
    "schoolYear" VARCHAR(255) NOT NULL,
    "yearlyResultId" UUID,
    "totalCredits" INTEGER DEFAULT 0,
    "averageGrade4" DOUBLE PRECISION DEFAULT 0,
    "averageGrade10" DOUBLE PRECISION DEFAULT 0,
    "cumulativeCredits" INTEGER DEFAULT 0,
    "cumulativeGrade4" DOUBLE PRECISION DEFAULT 0,
    "cumulativeGrade10" DOUBLE PRECISION DEFAULT 0,
    "debtCredits" INTEGER DEFAULT 0,
    "failedSubjects" INTEGER DEFAULT 0,
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "semester_results_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "semesters" (
    "id" UUID NOT NULL,
    "code" VARCHAR(255) NOT NULL,
    "schoolYear" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "semesters_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "students" (
    "id" UUID NOT NULL,
    "studentId" VARCHAR(255),
    "fullName" VARCHAR(255),
    "gender" VARCHAR(255),
    "birthday" TIMESTAMPTZ(6),
    "hometown" VARCHAR(255),
    "ethnicity" VARCHAR(255),
    "religion" VARCHAR(255),
    "currentAddress" VARCHAR(255),
    "placeOfBirth" VARCHAR(255),
    "phoneNumber" VARCHAR(255),
    "email" VARCHAR(255),
    "cccdNumber" VARCHAR(255),
    "partyMemberCardNumber" VARCHAR(255),
    "enrollment" INTEGER,
    "graduationDate" TIMESTAMPTZ(6),
    "unit" VARCHAR(255),
    "rank" VARCHAR(255),
    "positionGovernment" VARCHAR(255),
    "positionParty" VARCHAR(255),
    "fullPartyMember" TIMESTAMPTZ(6),
    "probationaryPartyMember" TIMESTAMPTZ(6),
    "dateOfEnlistment" TIMESTAMPTZ(6),
    "avatar" VARCHAR(255) DEFAULT 'https://i.pinimg.com/736x/81/09/3a/81093a0429e25b0ff579fa41aa96c421.jpg',
    "currentCpa4" DOUBLE PRECISION DEFAULT 0,
    "currentCpa10" DOUBLE PRECISION DEFAULT 0,
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),
    "classId" UUID,
    "organizationId" UUID,
    "universityId" UUID,
    "educationLevelId" UUID,

    CONSTRAINT "students_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "subject_results" (
    "id" UUID NOT NULL,
    "semesterResultId" UUID NOT NULL,
    "subjectCode" VARCHAR(255) NOT NULL,
    "subjectName" VARCHAR(255) NOT NULL,
    "credits" INTEGER NOT NULL,
    "letterGrade" VARCHAR(255) NOT NULL,
    "gradePoint4" DOUBLE PRECISION NOT NULL,
    "gradePoint10" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "subject_results_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "time_tables" (
    "id" UUID NOT NULL,
    "studentId" UUID NOT NULL,
    "schedules" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "time_tables_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tuition_fees" (
    "id" UUID NOT NULL,
    "studentId" UUID NOT NULL,
    "totalAmount" DECIMAL(18,2) NOT NULL,
    "semester" VARCHAR(255),
    "schoolYear" VARCHAR(255),
    "content" VARCHAR(255),
    "status" VARCHAR(255),
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "tuition_fees_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "universities" (
    "id" UUID NOT NULL,
    "universityCode" VARCHAR(255) NOT NULL,
    "universityName" VARCHAR(255) NOT NULL,
    "totalStudents" INTEGER DEFAULT 0,
    "status" VARCHAR(255) DEFAULT 'active',
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "universities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "username" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "isAdmin" BOOLEAN DEFAULT false,
    "studentId" UUID,
    "commanderId" UUID,
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),
    "deletedAt" TIMESTAMPTZ(6),

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "yearly_achievements" (
    "id" UUID NOT NULL,
    "studentId" UUID NOT NULL,
    "year" INTEGER NOT NULL,
    "decisionNumber" VARCHAR(255),
    "decisionDate" TIMESTAMPTZ(6),
    "title" VARCHAR(255) NOT NULL,
    "hasMinistryReward" BOOLEAN DEFAULT false,
    "hasNationalReward" BOOLEAN DEFAULT false,
    "notes" TEXT,
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "yearly_achievements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "yearly_results" (
    "id" UUID NOT NULL,
    "studentId" UUID NOT NULL,
    "schoolYear" VARCHAR(255) NOT NULL,
    "averageGrade4" DOUBLE PRECISION DEFAULT 0,
    "averageGrade10" DOUBLE PRECISION DEFAULT 0,
    "cumulativeGrade4" DOUBLE PRECISION DEFAULT 0,
    "cumulativeGrade10" DOUBLE PRECISION DEFAULT 0,
    "cumulativeCredits" INTEGER DEFAULT 0,
    "totalCredits" INTEGER DEFAULT 0,
    "totalSubjects" INTEGER DEFAULT 0,
    "passedSubjects" INTEGER DEFAULT 0,
    "failedSubjects" INTEGER DEFAULT 0,
    "debtCredits" INTEGER DEFAULT 0,
    "academicStatus" VARCHAR(255),
    "studentLevel" INTEGER DEFAULT 1,
    "semesterIds" UUID[] DEFAULT ARRAY[]::UUID[],
    "createdAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "yearly_results_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "achievement_profiles_studentId_key" ON "achievement_profiles"("studentId");

-- CreateIndex
CREATE UNIQUE INDEX "cut_rice_studentId_key" ON "cut_rice"("studentId");

-- CreateIndex
CREATE UNIQUE INDEX "semester_results_student_id_semester_school_year" ON "semester_results"("studentId", "semester", "schoolYear");

-- CreateIndex
CREATE UNIQUE INDEX "semesters_code_school_year" ON "semesters"("code", "schoolYear");

-- CreateIndex
CREATE UNIQUE INDEX "students_studentId_key" ON "students"("studentId");

-- CreateIndex
CREATE UNIQUE INDEX "students_fullName_key" ON "students"("fullName");

-- CreateIndex
CREATE UNIQUE INDEX "universities_universityCode_key" ON "universities"("universityCode");

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");

-- CreateIndex
CREATE UNIQUE INDEX "yearly_results_student_id_school_year" ON "yearly_results"("studentId", "schoolYear");

-- AddForeignKey
ALTER TABLE "achievement_profiles" ADD CONSTRAINT "achievement_profiles_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "achievements" ADD CONSTRAINT "achievements_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "classes" ADD CONSTRAINT "classes_educationLevelId_fkey" FOREIGN KEY ("educationLevelId") REFERENCES "education_levels"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cut_rice" ADD CONSTRAINT "cut_rice_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "education_levels" ADD CONSTRAINT "education_levels_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_universityId_fkey" FOREIGN KEY ("universityId") REFERENCES "universities"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scientific_initiatives" ADD CONSTRAINT "scientific_initiatives_yearlyAchievementId_fkey" FOREIGN KEY ("yearlyAchievementId") REFERENCES "yearly_achievements"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scientific_topics" ADD CONSTRAINT "scientific_topics_yearlyAchievementId_fkey" FOREIGN KEY ("yearlyAchievementId") REFERENCES "yearly_achievements"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "semester_results" ADD CONSTRAINT "semester_results_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "semester_results" ADD CONSTRAINT "semester_results_yearlyResultId_fkey" FOREIGN KEY ("yearlyResultId") REFERENCES "yearly_results"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "students" ADD CONSTRAINT "students_classId_fkey" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "students" ADD CONSTRAINT "students_educationLevelId_fkey" FOREIGN KEY ("educationLevelId") REFERENCES "education_levels"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "students" ADD CONSTRAINT "students_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "students" ADD CONSTRAINT "students_universityId_fkey" FOREIGN KEY ("universityId") REFERENCES "universities"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subject_results" ADD CONSTRAINT "subject_results_semesterResultId_fkey" FOREIGN KEY ("semesterResultId") REFERENCES "semester_results"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "time_tables" ADD CONSTRAINT "time_tables_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tuition_fees" ADD CONSTRAINT "tuition_fees_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_commanderId_fkey" FOREIGN KEY ("commanderId") REFERENCES "commanders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "yearly_achievements" ADD CONSTRAINT "yearly_achievements_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "yearly_results" ADD CONSTRAINT "yearly_results_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;
