const { DataTypes } = require("sequelize");
const { sequelize } = require("../services/sequelize");

const CutRice = sequelize.define(
  "cut_rice",
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    studentId: { type: DataTypes.UUID, allowNull: false, unique: true },
    weekly: {
      // cấu trúc { monday: { breakfast: bool, lunch: bool, dinner: bool }, ... }
      type: DataTypes.JSONB,
      allowNull: false,
      defaultValue: {},
    },
    isAutoGenerated: { type: DataTypes.BOOLEAN, defaultValue: true },
    lastUpdated: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    notes: DataTypes.STRING,
    createdAt: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    updatedAt: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  },
  { tableName: "cut_rice", timestamps: true }
);

module.exports = CutRice;
